/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author tefip
 */
public class Pantalla_Gerente extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Gerente
     */
    public Pantalla_Gerente() {
        initComponents();
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public void setBtnCerrarSesion(JButton btnCerrarSesion) {
        this.btnCerrarSesion = btnCerrarSesion;
    }

    public JButton getBtnClientes() {
        return btnClientes;
    }

    public void setBtnClientes(JButton btnClientes) {
        this.btnClientes = btnClientes;
    }

    public JButton getBtnEmpleaods() {
        return btnEmpleaods;
    }

    public void setBtnEmpleaods(JButton btnEmpleaods) {
        this.btnEmpleaods = btnEmpleaods;
    }

    public JButton getBtnMaquinas() {
        return btnMaquinas;
    }

    public void setBtnMaquinas(JButton btnMaquinas) {
        this.btnMaquinas = btnMaquinas;
    }

    public JButton getBtnProductos() {
        return btnProductos;
    }

    public void setBtnProductos(JButton btnProductos) {
        this.btnProductos = btnProductos;
    }

    public JButton getBtnReportes() {
        return btnReportes;
    }

    public void setBtnReportes(JButton btnReportes) {
        this.btnReportes = btnReportes;
    }

    public JButton getBtnServicios() {
        return btnServicios;
    }

    public void setBtnServicios(JButton btnServicios) {
        this.btnServicios = btnServicios;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlprincipal = new javax.swing.JPanel();
        pnlizquierdo = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        xxx = new javax.swing.JLabel();
        fdg = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblcedula = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        pnlsuperior = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        pnlmedio = new javax.swing.JPanel();
        lblcpanelc = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlempleados = new javax.swing.JPanel();
        pnlempleados2 = new javax.swing.JPanel();
        lblcemple = new javax.swing.JLabel();
        btnEmpleaods = new javax.swing.JButton();
        pnlclientes = new javax.swing.JPanel();
        pnlclientes1 = new javax.swing.JPanel();
        lblcemple1 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        pnlreportes = new javax.swing.JPanel();
        pnlreportes1 = new javax.swing.JPanel();
        lblcemple2 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        pnlservicios = new javax.swing.JPanel();
        pnlservicios1 = new javax.swing.JPanel();
        lblcemple3 = new javax.swing.JLabel();
        btnServicios = new javax.swing.JButton();
        pnlproductos = new javax.swing.JPanel();
        pnlproductos1 = new javax.swing.JPanel();
        lblcemple4 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        pnlmaquinas = new javax.swing.JPanel();
        pnlmaquinas1 = new javax.swing.JPanel();
        lblcemple5 = new javax.swing.JLabel();
        btnMaquinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlprincipal.setBackground(new java.awt.Color(240, 247, 250));
        pnlprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlizquierdo.setBackground(new java.awt.Color(0, 147, 185));

        lblcodigo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigo.setText("Cédula:");

        lblnombre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setText(".");

        xxx.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        xxx.setForeground(new java.awt.Color(255, 255, 255));
        xxx.setText("Nombre: ");

        fdg.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        fdg.setForeground(new java.awt.Color(255, 255, 255));
        fdg.setText("Apellido:");

        lblapellido.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(255, 255, 255));
        lblapellido.setText(".");

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Administrador");

        lblcedula.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        lblcedula.setForeground(new java.awt.Color(255, 255, 255));
        lblcedula.setText(".");

        foto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        foto.setForeground(new java.awt.Color(255, 255, 255));
        foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto.setText("ICON");

        javax.swing.GroupLayout pnlizquierdoLayout = new javax.swing.GroupLayout(pnlizquierdo);
        pnlizquierdo.setLayout(pnlizquierdoLayout);
        pnlizquierdoLayout.setHorizontalGroup(
            pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlizquierdoLayout.createSequentialGroup()
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlizquierdoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlizquierdoLayout.createSequentialGroup()
                                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(xxx)
                                    .addComponent(fdg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblapellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlizquierdoLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblcodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlizquierdoLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel8))))
                    .addGroup(pnlizquierdoLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlizquierdoLayout.setVerticalGroup(
            pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlizquierdoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(lblcedula))
                .addGap(18, 18, 18)
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xxx)
                    .addComponent(lblnombre))
                .addGap(18, 18, 18)
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fdg)
                    .addComponent(lblapellido))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlizquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 460));

        pnlsuperior.setBackground(new java.awt.Color(0, 147, 185));

        lbltitulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("LAVANDERÍA");

        javax.swing.GroupLayout pnlsuperiorLayout = new javax.swing.GroupLayout(pnlsuperior);
        pnlsuperior.setLayout(pnlsuperiorLayout);
        pnlsuperiorLayout.setHorizontalGroup(
            pnlsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsuperiorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbltitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlsuperiorLayout.setVerticalGroup(
            pnlsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlprincipal.add(pnlsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        pnlmedio.setBackground(new java.awt.Color(255, 255, 255));

        lblcpanelc.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        lblcpanelc.setForeground(new java.awt.Color(51, 51, 51));
        lblcpanelc.setText("Panel de navegación");

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 13)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(102, 102, 102));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setActionCommand("btnCerrarSesión");
        btnCerrarSesion.setBorder(null);

        javax.swing.GroupLayout pnlmedioLayout = new javax.swing.GroupLayout(pnlmedio);
        pnlmedio.setLayout(pnlmedioLayout);
        pnlmedioLayout.setHorizontalGroup(
            pnlmedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmedioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblcpanelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 688, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlmedioLayout.setVerticalGroup(
            pnlmedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcpanelc, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlprincipal.add(pnlmedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 960, 50));

        pnlempleados.setBackground(new java.awt.Color(255, 255, 255));
        pnlempleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlempleados2.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple.setText("Conoce tus empleados");

        javax.swing.GroupLayout pnlempleados2Layout = new javax.swing.GroupLayout(pnlempleados2);
        pnlempleados2.setLayout(pnlempleados2Layout);
        pnlempleados2Layout.setHorizontalGroup(
            pnlempleados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlempleados2Layout.setVerticalGroup(
            pnlempleados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlempleados2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcemple)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnEmpleaods.setBackground(new java.awt.Color(76, 226, 114));
        btnEmpleaods.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnEmpleaods.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleaods.setText("EMPLEADOS");
        btnEmpleaods.setToolTipText("");
        btnEmpleaods.setAutoscrolls(true);
        btnEmpleaods.setBorder(null);

        javax.swing.GroupLayout pnlempleadosLayout = new javax.swing.GroupLayout(pnlempleados);
        pnlempleados.setLayout(pnlempleadosLayout);
        pnlempleadosLayout.setHorizontalGroup(
            pnlempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlempleados2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmpleaods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlempleadosLayout.setVerticalGroup(
            pnlempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlempleadosLayout.createSequentialGroup()
                .addComponent(btnEmpleaods, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlempleados2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 150, -1));

        pnlclientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlclientes1.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple1.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple1.setText("Conoce tus clientes");

        javax.swing.GroupLayout pnlclientes1Layout = new javax.swing.GroupLayout(pnlclientes1);
        pnlclientes1.setLayout(pnlclientes1Layout);
        pnlclientes1Layout.setHorizontalGroup(
            pnlclientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlclientes1Layout.setVerticalGroup(
            pnlclientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlclientes1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcemple1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnClientes.setBackground(new java.awt.Color(160, 143, 231));
        btnClientes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("CLIENTES");
        btnClientes.setBorder(null);

        javax.swing.GroupLayout pnlclientesLayout = new javax.swing.GroupLayout(pnlclientes);
        pnlclientes.setLayout(pnlclientesLayout);
        pnlclientesLayout.setHorizontalGroup(
            pnlclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlclientes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlclientesLayout.setVerticalGroup(
            pnlclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlclientesLayout.createSequentialGroup()
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlclientes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 150, -1));

        pnlreportes.setBackground(new java.awt.Color(255, 255, 255));
        pnlreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlreportes1.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple2.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple2.setText("Revisa tus reportes");

        javax.swing.GroupLayout pnlreportes1Layout = new javax.swing.GroupLayout(pnlreportes1);
        pnlreportes1.setLayout(pnlreportes1Layout);
        pnlreportes1Layout.setHorizontalGroup(
            pnlreportes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlreportes1Layout.setVerticalGroup(
            pnlreportes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlreportes1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcemple2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnReportes.setBackground(new java.awt.Color(16, 178, 251));
        btnReportes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("REPORTES");
        btnReportes.setBorder(null);

        javax.swing.GroupLayout pnlreportesLayout = new javax.swing.GroupLayout(pnlreportes);
        pnlreportes.setLayout(pnlreportesLayout);
        pnlreportesLayout.setHorizontalGroup(
            pnlreportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlreportes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlreportesLayout.setVerticalGroup(
            pnlreportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlreportesLayout.createSequentialGroup()
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlreportes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 150, -1));

        pnlservicios.setBackground(new java.awt.Color(255, 255, 255));
        pnlservicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlservicios1.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple3.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple3.setText("Administra tus servicios");

        javax.swing.GroupLayout pnlservicios1Layout = new javax.swing.GroupLayout(pnlservicios1);
        pnlservicios1.setLayout(pnlservicios1Layout);
        pnlservicios1Layout.setHorizontalGroup(
            pnlservicios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        pnlservicios1Layout.setVerticalGroup(
            pnlservicios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlservicios1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcemple3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnServicios.setBackground(new java.awt.Color(245, 180, 48));
        btnServicios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios.setText("SERVICIOS");
        btnServicios.setBorder(null);

        javax.swing.GroupLayout pnlserviciosLayout = new javax.swing.GroupLayout(pnlservicios);
        pnlservicios.setLayout(pnlserviciosLayout);
        pnlserviciosLayout.setHorizontalGroup(
            pnlserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlservicios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlserviciosLayout.setVerticalGroup(
            pnlserviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlserviciosLayout.createSequentialGroup()
                .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlservicios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlservicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        pnlproductos.setBackground(new java.awt.Color(255, 255, 255));
        pnlproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlproductos1.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple4.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple4.setText("Administra tus productos");

        javax.swing.GroupLayout pnlproductos1Layout = new javax.swing.GroupLayout(pnlproductos1);
        pnlproductos1.setLayout(pnlproductos1Layout);
        pnlproductos1Layout.setHorizontalGroup(
            pnlproductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlproductos1Layout.setVerticalGroup(
            pnlproductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlproductos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcemple4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnProductos.setBackground(new java.awt.Color(129, 148, 163));
        btnProductos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("PRODUCTOS");
        btnProductos.setBorder(null);

        javax.swing.GroupLayout pnlproductosLayout = new javax.swing.GroupLayout(pnlproductos);
        pnlproductos.setLayout(pnlproductosLayout);
        pnlproductosLayout.setHorizontalGroup(
            pnlproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlproductos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlproductosLayout.setVerticalGroup(
            pnlproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlproductosLayout.createSequentialGroup()
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlproductos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 150, -1));

        pnlmaquinas.setBackground(new java.awt.Color(255, 255, 255));
        pnlmaquinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlmaquinas1.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple5.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple5.setText("Administra tus máquinas");

        javax.swing.GroupLayout pnlmaquinas1Layout = new javax.swing.GroupLayout(pnlmaquinas1);
        pnlmaquinas1.setLayout(pnlmaquinas1Layout);
        pnlmaquinas1Layout.setHorizontalGroup(
            pnlmaquinas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple5, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        pnlmaquinas1Layout.setVerticalGroup(
            pnlmaquinas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmaquinas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcemple5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnMaquinas.setBackground(new java.awt.Color(255, 147, 194));
        btnMaquinas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnMaquinas.setForeground(new java.awt.Color(255, 255, 255));
        btnMaquinas.setText("MÁQUINAS");
        btnMaquinas.setBorder(null);

        javax.swing.GroupLayout pnlmaquinasLayout = new javax.swing.GroupLayout(pnlmaquinas);
        pnlmaquinas.setLayout(pnlmaquinasLayout);
        pnlmaquinasLayout.setHorizontalGroup(
            pnlmaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmaquinas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlmaquinasLayout.setVerticalGroup(
            pnlmaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmaquinasLayout.createSequentialGroup()
                .addComponent(btnMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlmaquinas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlmaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 961, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleaods;
    private javax.swing.JButton btnMaquinas;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel fdg;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcemple;
    private javax.swing.JLabel lblcemple1;
    private javax.swing.JLabel lblcemple2;
    private javax.swing.JLabel lblcemple3;
    private javax.swing.JLabel lblcemple4;
    private javax.swing.JLabel lblcemple5;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcpanelc;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlclientes;
    private javax.swing.JPanel pnlclientes1;
    private javax.swing.JPanel pnlempleados;
    private javax.swing.JPanel pnlempleados2;
    private javax.swing.JPanel pnlizquierdo;
    private javax.swing.JPanel pnlmaquinas;
    private javax.swing.JPanel pnlmaquinas1;
    private javax.swing.JPanel pnlmedio;
    private javax.swing.JPanel pnlprincipal;
    private javax.swing.JPanel pnlproductos;
    private javax.swing.JPanel pnlproductos1;
    private javax.swing.JPanel pnlreportes;
    private javax.swing.JPanel pnlreportes1;
    private javax.swing.JPanel pnlservicios;
    private javax.swing.JPanel pnlservicios1;
    private javax.swing.JPanel pnlsuperior;
    private javax.swing.JLabel xxx;
    // End of variables declaration//GEN-END:variables
}
