/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author tefip
 */
public class Reportes_Individuales extends javax.swing.JFrame {

    /**
     * Creates new form Reportes_Individuales
     */
    public Reportes_Individuales() {
        initComponents();
    }

    public JButton getBtnCerrarSesion1() {
        return btnCerrarSesion1;
    }

    public void setBtnCerrarSesion1(JButton btnCerrarSesion1) {
        this.btnCerrarSesion1 = btnCerrarSesion1;
    }

    public JButton getBtnClientes1() {
        return btnClientes1;
    }

    public void setBtnClientes1(JButton btnClientes1) {
        this.btnClientes1 = btnClientes1;
    }

    public JButton getBtnEmpleaods1() {
        return btnEmpleaods1;
    }

    public void setBtnEmpleaods1(JButton btnEmpleaods1) {
        this.btnEmpleaods1 = btnEmpleaods1;
    }

    public JButton getBtnMaquinas1() {
        return btnMaquinas1;
    }

    public void setBtnMaquinas1(JButton btnMaquinas1) {
        this.btnMaquinas1 = btnMaquinas1;
    }

    public JButton getBtnProductos1() {
        return btnProductos1;
    }

    public void setBtnProductos1(JButton btnProductos1) {
        this.btnProductos1 = btnProductos1;
    }

    public JButton getBtnReportes1() {
        return btnReportes1;
    }

    public void setBtnReportes1(JButton btnReportes1) {
        this.btnReportes1 = btnReportes1;
    }

    public JButton getBtnServicios1() {
        return btnServicios1;
    }

    public void setBtnServicios1(JButton btnServicios1) {
        this.btnServicios1 = btnServicios1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlprincipal3 = new javax.swing.JPanel();
        pnlsuperior1 = new javax.swing.JPanel();
        lbltitulo1 = new javax.swing.JLabel();
        pnlmedio1 = new javax.swing.JPanel();
        lblcpanelc1 = new javax.swing.JLabel();
        btnCerrarSesion1 = new javax.swing.JButton();
        pnlempleados1 = new javax.swing.JPanel();
        pnlempleados3 = new javax.swing.JPanel();
        lblcemple6 = new javax.swing.JLabel();
        btnEmpleaods1 = new javax.swing.JButton();
        pnlclientes2 = new javax.swing.JPanel();
        pnlclientes3 = new javax.swing.JPanel();
        lblcemple7 = new javax.swing.JLabel();
        btnClientes1 = new javax.swing.JButton();
        pnlreportes2 = new javax.swing.JPanel();
        pnlreportes3 = new javax.swing.JPanel();
        lblcemple8 = new javax.swing.JLabel();
        btnReportes1 = new javax.swing.JButton();
        pnlservicios2 = new javax.swing.JPanel();
        pnlservicios3 = new javax.swing.JPanel();
        lblcemple9 = new javax.swing.JLabel();
        btnServicios1 = new javax.swing.JButton();
        pnlproductos2 = new javax.swing.JPanel();
        pnlproductos3 = new javax.swing.JPanel();
        lblcemple10 = new javax.swing.JLabel();
        btnProductos1 = new javax.swing.JButton();
        pnlmaquinas2 = new javax.swing.JPanel();
        pnlmaquinas3 = new javax.swing.JPanel();
        lblcemple11 = new javax.swing.JLabel();
        btnMaquinas1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlprincipal3.setBackground(new java.awt.Color(240, 247, 250));
        pnlprincipal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlsuperior1.setBackground(new java.awt.Color(0, 147, 185));

        lbltitulo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        lbltitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo1.setText("LAVANDERÍA");

        javax.swing.GroupLayout pnlsuperior1Layout = new javax.swing.GroupLayout(pnlsuperior1);
        pnlsuperior1.setLayout(pnlsuperior1Layout);
        pnlsuperior1Layout.setHorizontalGroup(
            pnlsuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsuperior1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbltitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlsuperior1Layout.setVerticalGroup(
            pnlsuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlprincipal3.add(pnlsuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 60));

        pnlmedio1.setBackground(new java.awt.Color(255, 255, 255));

        lblcpanelc1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        lblcpanelc1.setForeground(new java.awt.Color(51, 51, 51));
        lblcpanelc1.setText("Panel de navegación");

        btnCerrarSesion1.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 13)); // NOI18N
        btnCerrarSesion1.setForeground(new java.awt.Color(102, 102, 102));
        btnCerrarSesion1.setText("Salir");
        btnCerrarSesion1.setActionCommand("btnCerrarSesión");
        btnCerrarSesion1.setBorder(null);

        javax.swing.GroupLayout pnlmedio1Layout = new javax.swing.GroupLayout(pnlmedio1);
        pnlmedio1.setLayout(pnlmedio1Layout);
        pnlmedio1Layout.setHorizontalGroup(
            pnlmedio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmedio1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblcpanelc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlmedio1Layout.setVerticalGroup(
            pnlmedio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcpanelc1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnCerrarSesion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlprincipal3.add(pnlmedio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 760, 50));

        pnlempleados1.setBackground(new java.awt.Color(255, 255, 255));
        pnlempleados1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlempleados3.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple6.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple6.setText("Reporte de Empleados");

        javax.swing.GroupLayout pnlempleados3Layout = new javax.swing.GroupLayout(pnlempleados3);
        pnlempleados3.setLayout(pnlempleados3Layout);
        pnlempleados3Layout.setHorizontalGroup(
            pnlempleados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlempleados3Layout.setVerticalGroup(
            pnlempleados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlempleados3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcemple6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnEmpleaods1.setBackground(new java.awt.Color(76, 226, 114));
        btnEmpleaods1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnEmpleaods1.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleaods1.setText("EMPLEADOS");
        btnEmpleaods1.setToolTipText("");
        btnEmpleaods1.setAutoscrolls(true);
        btnEmpleaods1.setBorder(null);

        javax.swing.GroupLayout pnlempleados1Layout = new javax.swing.GroupLayout(pnlempleados1);
        pnlempleados1.setLayout(pnlempleados1Layout);
        pnlempleados1Layout.setHorizontalGroup(
            pnlempleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlempleados3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmpleaods1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlempleados1Layout.setVerticalGroup(
            pnlempleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlempleados1Layout.createSequentialGroup()
                .addComponent(btnEmpleaods1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlempleados3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal3.add(pnlempleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        pnlclientes2.setBackground(new java.awt.Color(255, 255, 255));
        pnlclientes2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlclientes3.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple7.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple7.setText("Reporte de Clientes");

        javax.swing.GroupLayout pnlclientes3Layout = new javax.swing.GroupLayout(pnlclientes3);
        pnlclientes3.setLayout(pnlclientes3Layout);
        pnlclientes3Layout.setHorizontalGroup(
            pnlclientes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlclientes3Layout.setVerticalGroup(
            pnlclientes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlclientes3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcemple7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnClientes1.setBackground(new java.awt.Color(160, 143, 231));
        btnClientes1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnClientes1.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes1.setText("CLIENTES");
        btnClientes1.setBorder(null);

        javax.swing.GroupLayout pnlclientes2Layout = new javax.swing.GroupLayout(pnlclientes2);
        pnlclientes2.setLayout(pnlclientes2Layout);
        pnlclientes2Layout.setHorizontalGroup(
            pnlclientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlclientes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClientes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlclientes2Layout.setVerticalGroup(
            pnlclientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlclientes2Layout.createSequentialGroup()
                .addComponent(btnClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlclientes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal3.add(pnlclientes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 150, -1));

        pnlreportes2.setBackground(new java.awt.Color(255, 255, 255));
        pnlreportes2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlreportes3.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple8.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple8.setText("Reporte de Ordenes");

        javax.swing.GroupLayout pnlreportes3Layout = new javax.swing.GroupLayout(pnlreportes3);
        pnlreportes3.setLayout(pnlreportes3Layout);
        pnlreportes3Layout.setHorizontalGroup(
            pnlreportes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlreportes3Layout.setVerticalGroup(
            pnlreportes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlreportes3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcemple8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnReportes1.setBackground(new java.awt.Color(16, 178, 251));
        btnReportes1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnReportes1.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes1.setText("REPORTES");
        btnReportes1.setBorder(null);

        javax.swing.GroupLayout pnlreportes2Layout = new javax.swing.GroupLayout(pnlreportes2);
        pnlreportes2.setLayout(pnlreportes2Layout);
        pnlreportes2Layout.setHorizontalGroup(
            pnlreportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlreportes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlreportes2Layout.setVerticalGroup(
            pnlreportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlreportes2Layout.createSequentialGroup()
                .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlreportes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal3.add(pnlreportes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 150, -1));

        pnlservicios2.setBackground(new java.awt.Color(255, 255, 255));
        pnlservicios2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlservicios3.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple9.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple9.setText("Reporte de Servicios");

        javax.swing.GroupLayout pnlservicios3Layout = new javax.swing.GroupLayout(pnlservicios3);
        pnlservicios3.setLayout(pnlservicios3Layout);
        pnlservicios3Layout.setHorizontalGroup(
            pnlservicios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        pnlservicios3Layout.setVerticalGroup(
            pnlservicios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlservicios3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcemple9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnServicios1.setBackground(new java.awt.Color(245, 180, 48));
        btnServicios1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnServicios1.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios1.setText("SERVICIOS");
        btnServicios1.setBorder(null);

        javax.swing.GroupLayout pnlservicios2Layout = new javax.swing.GroupLayout(pnlservicios2);
        pnlservicios2.setLayout(pnlservicios2Layout);
        pnlservicios2Layout.setHorizontalGroup(
            pnlservicios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlservicios3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnServicios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlservicios2Layout.setVerticalGroup(
            pnlservicios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlservicios2Layout.createSequentialGroup()
                .addComponent(btnServicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlservicios3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal3.add(pnlservicios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        pnlproductos2.setBackground(new java.awt.Color(255, 255, 255));
        pnlproductos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlproductos3.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple10.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple10.setText("Reporte de Productos");

        javax.swing.GroupLayout pnlproductos3Layout = new javax.swing.GroupLayout(pnlproductos3);
        pnlproductos3.setLayout(pnlproductos3Layout);
        pnlproductos3Layout.setHorizontalGroup(
            pnlproductos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlproductos3Layout.setVerticalGroup(
            pnlproductos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlproductos3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcemple10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnProductos1.setBackground(new java.awt.Color(129, 148, 163));
        btnProductos1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnProductos1.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos1.setText("PRODUCTOS");
        btnProductos1.setBorder(null);

        javax.swing.GroupLayout pnlproductos2Layout = new javax.swing.GroupLayout(pnlproductos2);
        pnlproductos2.setLayout(pnlproductos2Layout);
        pnlproductos2Layout.setHorizontalGroup(
            pnlproductos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlproductos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlproductos2Layout.setVerticalGroup(
            pnlproductos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlproductos2Layout.createSequentialGroup()
                .addComponent(btnProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlproductos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal3.add(pnlproductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 150, -1));

        pnlmaquinas2.setBackground(new java.awt.Color(255, 255, 255));
        pnlmaquinas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlmaquinas3.setBackground(new java.awt.Color(255, 255, 255));

        lblcemple11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lblcemple11.setForeground(new java.awt.Color(102, 102, 102));
        lblcemple11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcemple11.setText("Reporte de Máquinas");

        javax.swing.GroupLayout pnlmaquinas3Layout = new javax.swing.GroupLayout(pnlmaquinas3);
        pnlmaquinas3.setLayout(pnlmaquinas3Layout);
        pnlmaquinas3Layout.setHorizontalGroup(
            pnlmaquinas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcemple11, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        pnlmaquinas3Layout.setVerticalGroup(
            pnlmaquinas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmaquinas3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcemple11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnMaquinas1.setBackground(new java.awt.Color(255, 147, 194));
        btnMaquinas1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        btnMaquinas1.setForeground(new java.awt.Color(255, 255, 255));
        btnMaquinas1.setText("MÁQUINAS");
        btnMaquinas1.setBorder(null);

        javax.swing.GroupLayout pnlmaquinas2Layout = new javax.swing.GroupLayout(pnlmaquinas2);
        pnlmaquinas2.setLayout(pnlmaquinas2Layout);
        pnlmaquinas2Layout.setHorizontalGroup(
            pnlmaquinas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmaquinas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMaquinas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlmaquinas2Layout.setVerticalGroup(
            pnlmaquinas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmaquinas2Layout.createSequentialGroup()
                .addComponent(btnMaquinas1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlmaquinas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlprincipal3.add(pnlmaquinas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlprincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlprincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion1;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnEmpleaods1;
    private javax.swing.JButton btnMaquinas1;
    private javax.swing.JButton btnProductos1;
    private javax.swing.JButton btnReportes1;
    private javax.swing.JButton btnServicios1;
    private javax.swing.JLabel fdg1;
    private javax.swing.JLabel fdg2;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblapellido1;
    private javax.swing.JLabel lblapellido2;
    private javax.swing.JLabel lblcedula1;
    private javax.swing.JLabel lblcedula2;
    private javax.swing.JLabel lblcemple10;
    private javax.swing.JLabel lblcemple11;
    private javax.swing.JLabel lblcemple6;
    private javax.swing.JLabel lblcemple7;
    private javax.swing.JLabel lblcemple8;
    private javax.swing.JLabel lblcemple9;
    private javax.swing.JLabel lblcodigo1;
    private javax.swing.JLabel lblcodigo2;
    private javax.swing.JLabel lblcpanelc1;
    private javax.swing.JLabel lblnombre1;
    private javax.swing.JLabel lblnombre2;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JPanel pnlclientes2;
    private javax.swing.JPanel pnlclientes3;
    private javax.swing.JPanel pnlempleados1;
    private javax.swing.JPanel pnlempleados3;
    private javax.swing.JPanel pnlizquierdo1;
    private javax.swing.JPanel pnlizquierdo2;
    private javax.swing.JPanel pnlmaquinas2;
    private javax.swing.JPanel pnlmaquinas3;
    private javax.swing.JPanel pnlmedio1;
    private javax.swing.JPanel pnlprincipal1;
    private javax.swing.JPanel pnlprincipal2;
    private javax.swing.JPanel pnlprincipal3;
    private javax.swing.JPanel pnlproductos2;
    private javax.swing.JPanel pnlproductos3;
    private javax.swing.JPanel pnlreportes2;
    private javax.swing.JPanel pnlreportes3;
    private javax.swing.JPanel pnlservicios2;
    private javax.swing.JPanel pnlservicios3;
    private javax.swing.JPanel pnlsuperior1;
    private javax.swing.JLabel xxx1;
    private javax.swing.JLabel xxx2;
    // End of variables declaration//GEN-END:variables
}
