/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author tefip
 */
public class VReportes extends javax.swing.JFrame {

    /**
     * Creates new form VReportes
     */
    public VReportes() {
        initComponents();
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnOrdenDia() {
        return btnOrdenDia;
    }

    public void setBtnOrdenDia(JButton btnOrdenDia) {
        this.btnOrdenDia = btnOrdenDia;
    }

    public JButton getBtnOrdenTrabajo() {
        return btnOrdenTrabajo;
    }

    public void setBtnOrdenTrabajo(JButton btnOrdenTrabajo) {
        this.btnOrdenTrabajo = btnOrdenTrabajo;
    }

    public JButton getBtnReporteMaterial() {
        return btnReporteMaterial;
    }

    public void setBtnReporteMaterial(JButton btnReporteMaterial) {
        this.btnReporteMaterial = btnReporteMaterial;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlprincipal = new javax.swing.JPanel();
        pnlsuperior = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        pnlmedio = new javax.swing.JPanel();
        lblreportes = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        pnlizquierdo = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        xxx = new javax.swing.JLabel();
        fdg = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblcedula = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        btnOrdenTrabajo = new javax.swing.JButton();
        btnOrdenDia = new javax.swing.JButton();
        btnReporteMaterial = new javax.swing.JButton();
        pnlcambiante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlprincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlsuperior.setBackground(new java.awt.Color(0, 147, 185));

        lbltitulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("LAVANDERÍA");

        javax.swing.GroupLayout pnlsuperiorLayout = new javax.swing.GroupLayout(pnlsuperior);
        pnlsuperior.setLayout(pnlsuperiorLayout);
        pnlsuperiorLayout.setHorizontalGroup(
            pnlsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsuperiorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbltitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlsuperiorLayout.setVerticalGroup(
            pnlsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlprincipal.add(pnlsuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        pnlmedio.setBackground(new java.awt.Color(255, 255, 255));
        pnlmedio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblreportes.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 13)); // NOI18N
        lblreportes.setForeground(new java.awt.Color(51, 51, 51));
        lblreportes.setText("Panel de control / Reportes");
        pnlmedio.add(lblreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 56));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 26)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(102, 102, 102));
        btnAtras.setText("  ←");
        btnAtras.setBorder(null);
        pnlmedio.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 50, 50));

        pnlprincipal.add(pnlmedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 960, 50));

        pnlizquierdo.setBackground(new java.awt.Color(0, 147, 185));

        lblcodigo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblcodigo.setText("Cédula:");

        lblnombre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setText(".");

        xxx.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        xxx.setForeground(new java.awt.Color(255, 255, 255));
        xxx.setText("Nombre: ");

        fdg.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        fdg.setForeground(new java.awt.Color(255, 255, 255));
        fdg.setText("Apellido:");

        lblapellido.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(255, 255, 255));
        lblapellido.setText(".");

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Administrador");

        lblcedula.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        lblcedula.setForeground(new java.awt.Color(255, 255, 255));
        lblcedula.setText(".");

        foto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        foto.setForeground(new java.awt.Color(255, 255, 255));
        foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto.setText("xoxo");

        btnOrdenTrabajo.setBackground(new java.awt.Color(44, 202, 251));
        btnOrdenTrabajo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnOrdenTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenTrabajo.setText("ÓRDENES DE TRABAJO");
        btnOrdenTrabajo.setBorder(null);

        btnOrdenDia.setBackground(new java.awt.Color(44, 202, 251));
        btnOrdenDia.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnOrdenDia.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenDia.setText("ÓRDENES DEL DÍA");
        btnOrdenDia.setBorder(null);

        btnReporteMaterial.setBackground(new java.awt.Color(44, 202, 251));
        btnReporteMaterial.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnReporteMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteMaterial.setText("REPORTES");
        btnReporteMaterial.setBorder(null);

        javax.swing.GroupLayout pnlizquierdoLayout = new javax.swing.GroupLayout(pnlizquierdo);
        pnlizquierdo.setLayout(pnlizquierdoLayout);
        pnlizquierdoLayout.setHorizontalGroup(
            pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlizquierdoLayout.createSequentialGroup()
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlizquierdoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlizquierdoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(xxx)
                        .addGap(6, 6, 6)
                        .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlizquierdoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(fdg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlizquierdoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblcodigo)
                        .addGap(18, 18, 18)
                        .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlizquierdoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOrdenTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrdenDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReporteMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlizquierdoLayout.setVerticalGroup(
            pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlizquierdoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedula)
                    .addComponent(lblcodigo))
                .addGap(18, 18, 18)
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xxx)
                    .addComponent(lblnombre))
                .addGap(18, 18, 18)
                .addGroup(pnlizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapellido)
                    .addComponent(fdg))
                .addGap(71, 71, 71)
                .addComponent(btnOrdenTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrdenDia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReporteMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlprincipal.add(pnlizquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 510));

        pnlcambiante.setBackground(new java.awt.Color(240, 247, 250));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAVAFLASH");

        javax.swing.GroupLayout pnlcambianteLayout = new javax.swing.GroupLayout(pnlcambiante);
        pnlcambiante.setLayout(pnlcambianteLayout);
        pnlcambianteLayout.setHorizontalGroup(
            pnlcambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcambianteLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
        );
        pnlcambianteLayout.setVerticalGroup(
            pnlcambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcambianteLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pnlprincipal.add(pnlcambiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 680, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnOrdenDia;
    private javax.swing.JButton btnOrdenTrabajo;
    private javax.swing.JButton btnReporteMaterial;
    private javax.swing.JLabel fdg;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblreportes;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlcambiante;
    private javax.swing.JPanel pnlizquierdo;
    private javax.swing.JPanel pnlmedio;
    private javax.swing.JPanel pnlprincipal;
    private javax.swing.JPanel pnlsuperior;
    private javax.swing.JLabel xxx;
    // End of variables declaration//GEN-END:variables
}
